return {
	TelescopeNormal = { link = "PickerResultsNormal" },
	TelescopeBorder = { link = "PickerResultsBorder" },
	TelescopeMatching = { link = "Directory" },
	TelescopeMultiSelection = { link = "CursorLineNr" },
	TelescopePromptNormal = { link = "PickerPromptNormal" },
	TelescopePromptBorder = { link = "PickerPromptBorder" },
	TelescopePromptTitle = { link = "PickerPromptTitle" },
	TelescopePromptCounter = { link = "CursorLineNr" },
	TelescopePromptPrefix = { link = "CursorLineNr" },
	TelescopeSelection = { link = "PickerSelection" },
	TelescopeSelectionCaret = { link = "Exception" },
	TelescopeResultsNormal = { link = "PickerResultsNormal" },
	TelescopeResultsBorder = { link = "PickerResultsBorder" },
	TelescopeResultsTitle = { link = "PickerResultsTitle" },
	TelescopePreviewNormal = { link = "PickerPreviewNormal" },
	TelescopePreviewBorder = { link = "PickerPreviewBorder" },
	TelescopePreviewTitle = { link = "PickerPreviewTitle" },
	TelescopeResultsComment = { link = "Directory" },
	TelescopePathSeparator = { link = "Directory" },
	TelescopeResultsSpecialComment = { link = "Comment" },
}
