return {
	FzfLuaNormal = { link = "PickerPromptNormal" },
	FzfLuaBorder = { link = "PickerResultsBorder" },
	FzfLuaTitle = { link = "PickerResultsTitle" },
	FzfLuaPreviewNormal = { link = "PickerPreviewNormal" },
	FzfLuaPreviewBorder = { link = "PickerPreviewBorder" },
	FzfLuaPreviewTitle = { link = "PickerPreviewTitle" },
	FzfLuaCursor = { link = "Cursor" },
	FzfLuaCursorLine = { link = "PickerSelection" },
	FzfLuaCursorLineNr = { link = "CursorLineNr" },
	FzfLuaSearch = { link = "FloatTitle" },
	-- FzfLuaScrollBorderEmpty = { link = 'FloatTitle' },
	-- FzfLuaScrollBorderFull = { link = 'FloatTitle' },
	-- FzfLuaScrollFloatEmpty = { link = 'FloatTitle' },
	-- FzfLuaScrollFloatFull = { link = 'FloatTitle' },
	-- FzfLuaHelpNormal = { link = 'TelescopeNormal' },
	-- FzfLuaHelpBorder = { link = 'TelescopeBorder' },
	-- FzfLuaHeaderBind = { link = 'FloatTitle' },
	FzfLuaHeaderText = { link = "CursorLineNr" },
	-- FzfLuaBufName = { link = 'Exception' },
	-- FzfLuaBufNr = { link = 'LineNr' },
	-- FzfLuaBufLineNr = { link = 'LineNr' },
	-- FzfLuaBufFlagCur = { link = 'Exception' },
	-- FzfLuaBufFlagAlt = { link = 'Exception' },
	FzfLuaTabTitle = { link = "FloatTitle" },
	FzfLuaTabMarker = { link = "FloatTitle" },
}
